In [1]:
import numpy as np

a = np.random.randn(5)

In [3]:
print(a)

[-0.49851456  0.33461877 -1.14056334  0.95017248  0.40495554]


In [4]:
a.shape

(5,)

In [9]:
b = np.random.randn(5, 1)
print(b)

[[-1.22546781]
 [ 1.56247955]
 [ 0.13960244]
 [-1.02390822]
 [ 1.08953619]]


In [10]:
c = np.random.randn(1,5)
print(c)

[[-1.05502627 -0.61726256  1.43302388  0.17551493 -1.09303304]]


In [14]:
assert(b.shape == (5, 1))

In [15]:
a

array([-0.49851456,  0.33461877, -1.14056334,  0.95017248,  0.40495554])

In [17]:
a = a.reshape(5,1)

In [18]:
a

array([[-0.49851456],
       [ 0.33461877],
       [-1.14056334],
       [ 0.95017248],
       [ 0.40495554]])

In [25]:
a = np.random.randn(2, 3)
b = np.random.randn(2, 1)
c = a + b
c

array([[-1.53750509, -1.61882216, -0.99353577],
       [-3.27341236,  1.75438142, -1.92799449]])

In [24]:
c

array([[-0.04182051, -0.14153111, -0.14049218],
       [-0.1235974 , -1.4841339 ,  0.19926315],
       [-0.05572233, -0.81643619,  0.13289043]])

In [27]:
d = np.random.randn(3, 4)
e = np.random.randn(4, 1)

c = d + e.T

In [28]:
c

array([[-3.17576428, -0.59569914, -1.71794532, -1.05535826],
       [-1.87367206,  0.12867802, -2.94555047, -0.30730645],
       [-1.80971556, -0.75872565, -2.59286936, -0.06989704]])

In [29]:
d

array([[-1.97977569, -0.01198657,  0.40231485, -1.5786974 ],
       [-0.67768347,  0.71239059, -0.8252903 , -0.83064558],
       [-0.61372696, -0.17501307, -0.47260919, -0.59323618]])

In [30]:
d.T

array([[-1.97977569, -0.67768347, -0.61372696],
       [-0.01198657,  0.71239059, -0.17501307],
       [ 0.40231485, -0.8252903 , -0.47260919],
       [-1.5786974 , -0.83064558, -0.59323618]])